"""Crosswalk from the threat catalog to OWASP Agentic Top 10 and MITRE ATLAS entries."""

from __future__ import annotations

from collections import defaultdict

from agentsec.threatmodel.render import Threat, load_catalog, load_frameworks


def _row(cells: list[str]) -> str:
    return "| " + " | ".join(cells) + " |"


def crosswalk_markdown() -> str:
    """Which catalog threats, toolkit controls and fuzzer categories back each framework entry.

    Mapping a threat to an entry means "this threat is an instance of, or contributes to, that
    entry". It does not mean the toolkit mitigates the entry: the *Toolkit controls* column names
    what helps, and entries with no threat are listed as gaps rather than omitted.
    """
    fw = load_frameworks()
    catalog = load_catalog()
    lines = [
        "# Framework crosswalk",
        "",
        "Generated by `agentsec threatmodel crosswalk`. A mapping means the catalog threat is an",
        "instance of, or contributes to, the framework entry. It does not mean the entry is",
        "mitigated: see *Toolkit controls* for what helps. Entries with no catalog threat are gaps.",
        "",
    ]

    for key in ("owasp_agentic", "mitre_atlas"):
        meta = fw[key]
        by_id: dict[str, list[Threat]] = defaultdict(list)
        for t in catalog:
            for ref in getattr(t, key):
                by_id[ref].append(t)
        version = f", content {meta['version']}" if "version" in meta else ""
        lines += [f"## {meta['title']}{version}", "", f"Source: <{meta['source']}>", ""]
        if key == "mitre_atlas":
            lines += [
                "Only techniques referenced by the catalog are listed; ATLAS has many more.",
                "",
            ]
        lines += [
            _row(["Id", "Name", "Catalog threats", "Toolkit controls", "Fuzzer categories"]),
            _row(["---"] * 5),
        ]
        for ref, name in meta["items"].items():
            threats = by_id.get(ref, [])
            controls = sorted({c for t in threats for c in t.toolkit})
            fuzz = sorted({c for t in threats for c in t.fuzz})
            lines.append(
                _row(
                    [
                        ref,
                        name.replace("|", "\\|"),
                        ", ".join(t.id for t in threats) or "**gap: no catalog threat**",
                        ", ".join(f"`{c}`" for c in controls) or "-",
                        ", ".join(fuzz) or "-",
                    ]
                )
            )
        lines.append("")
    return "\n".join(lines)
